# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ntallaris/CLionProjects/AbstractWithSharedObjects

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ntallaris/CLionProjects/AbstractWithSharedObjects

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/ntallaris/Downloads/CLion-2018.3.4/clion-2018.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ntallaris/CLionProjects/AbstractWithSharedObjects/CMakeFiles /home/ntallaris/CLionProjects/AbstractWithSharedObjects/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ntallaris/CLionProjects/AbstractWithSharedObjects/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MapFunctions

# Build rule for target.
MapFunctions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MapFunctions
.PHONY : MapFunctions

# fast build rule for target.
MapFunctions/fast:
	$(MAKE) -f CMakeFiles/MapFunctions.dir/build.make CMakeFiles/MapFunctions.dir/build
.PHONY : MapFunctions/fast

#=============================================================================
# Target rules for targets named AbstractWithSharedObjects

# Build rule for target.
AbstractWithSharedObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AbstractWithSharedObjects
.PHONY : AbstractWithSharedObjects

# fast build rule for target.
AbstractWithSharedObjects/fast:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/build
.PHONY : AbstractWithSharedObjects/fast

SharedLibraries/mapFunctions.o: SharedLibraries/mapFunctions.cpp.o

.PHONY : SharedLibraries/mapFunctions.o

# target to build an object file
SharedLibraries/mapFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/MapFunctions.dir/build.make CMakeFiles/MapFunctions.dir/SharedLibraries/mapFunctions.cpp.o
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedLibraries/mapFunctions.cpp.o
.PHONY : SharedLibraries/mapFunctions.cpp.o

SharedLibraries/mapFunctions.i: SharedLibraries/mapFunctions.cpp.i

.PHONY : SharedLibraries/mapFunctions.i

# target to preprocess a source file
SharedLibraries/mapFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/MapFunctions.dir/build.make CMakeFiles/MapFunctions.dir/SharedLibraries/mapFunctions.cpp.i
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedLibraries/mapFunctions.cpp.i
.PHONY : SharedLibraries/mapFunctions.cpp.i

SharedLibraries/mapFunctions.s: SharedLibraries/mapFunctions.cpp.s

.PHONY : SharedLibraries/mapFunctions.s

# target to generate assembly for a file
SharedLibraries/mapFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/MapFunctions.dir/build.make CMakeFiles/MapFunctions.dir/SharedLibraries/mapFunctions.cpp.s
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedLibraries/mapFunctions.cpp.s
.PHONY : SharedLibraries/mapFunctions.cpp.s

SharedMemory/Pointer.o: SharedMemory/Pointer.cpp.o

.PHONY : SharedMemory/Pointer.o

# target to build an object file
SharedMemory/Pointer.cpp.o:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/Pointer.cpp.o
.PHONY : SharedMemory/Pointer.cpp.o

SharedMemory/Pointer.i: SharedMemory/Pointer.cpp.i

.PHONY : SharedMemory/Pointer.i

# target to preprocess a source file
SharedMemory/Pointer.cpp.i:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/Pointer.cpp.i
.PHONY : SharedMemory/Pointer.cpp.i

SharedMemory/Pointer.s: SharedMemory/Pointer.cpp.s

.PHONY : SharedMemory/Pointer.s

# target to generate assembly for a file
SharedMemory/Pointer.cpp.s:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/Pointer.cpp.s
.PHONY : SharedMemory/Pointer.cpp.s

SharedMemory/PointerList.o: SharedMemory/PointerList.cpp.o

.PHONY : SharedMemory/PointerList.o

# target to build an object file
SharedMemory/PointerList.cpp.o:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/PointerList.cpp.o
.PHONY : SharedMemory/PointerList.cpp.o

SharedMemory/PointerList.i: SharedMemory/PointerList.cpp.i

.PHONY : SharedMemory/PointerList.i

# target to preprocess a source file
SharedMemory/PointerList.cpp.i:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/PointerList.cpp.i
.PHONY : SharedMemory/PointerList.cpp.i

SharedMemory/PointerList.s: SharedMemory/PointerList.cpp.s

.PHONY : SharedMemory/PointerList.s

# target to generate assembly for a file
SharedMemory/PointerList.cpp.s:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/PointerList.cpp.s
.PHONY : SharedMemory/PointerList.cpp.s

SharedMemory/SharedMemoryGenerator.o: SharedMemory/SharedMemoryGenerator.cpp.o

.PHONY : SharedMemory/SharedMemoryGenerator.o

# target to build an object file
SharedMemory/SharedMemoryGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/SharedMemoryGenerator.cpp.o
.PHONY : SharedMemory/SharedMemoryGenerator.cpp.o

SharedMemory/SharedMemoryGenerator.i: SharedMemory/SharedMemoryGenerator.cpp.i

.PHONY : SharedMemory/SharedMemoryGenerator.i

# target to preprocess a source file
SharedMemory/SharedMemoryGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/SharedMemoryGenerator.cpp.i
.PHONY : SharedMemory/SharedMemoryGenerator.cpp.i

SharedMemory/SharedMemoryGenerator.s: SharedMemory/SharedMemoryGenerator.cpp.s

.PHONY : SharedMemory/SharedMemoryGenerator.s

# target to generate assembly for a file
SharedMemory/SharedMemoryGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/SharedMemoryGenerator.cpp.s
.PHONY : SharedMemory/SharedMemoryGenerator.cpp.s

SharedMemory/resources/SharedMemoryData.o: SharedMemory/resources/SharedMemoryData.cpp.o

.PHONY : SharedMemory/resources/SharedMemoryData.o

# target to build an object file
SharedMemory/resources/SharedMemoryData.cpp.o:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/resources/SharedMemoryData.cpp.o
.PHONY : SharedMemory/resources/SharedMemoryData.cpp.o

SharedMemory/resources/SharedMemoryData.i: SharedMemory/resources/SharedMemoryData.cpp.i

.PHONY : SharedMemory/resources/SharedMemoryData.i

# target to preprocess a source file
SharedMemory/resources/SharedMemoryData.cpp.i:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/resources/SharedMemoryData.cpp.i
.PHONY : SharedMemory/resources/SharedMemoryData.cpp.i

SharedMemory/resources/SharedMemoryData.s: SharedMemory/resources/SharedMemoryData.cpp.s

.PHONY : SharedMemory/resources/SharedMemoryData.s

# target to generate assembly for a file
SharedMemory/resources/SharedMemoryData.cpp.s:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/SharedMemory/resources/SharedMemoryData.cpp.s
.PHONY : SharedMemory/resources/SharedMemoryData.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/AbstractWithSharedObjects.dir/build.make CMakeFiles/AbstractWithSharedObjects.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... MapFunctions"
	@echo "... edit_cache"
	@echo "... AbstractWithSharedObjects"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... SharedLibraries/mapFunctions.o"
	@echo "... SharedLibraries/mapFunctions.i"
	@echo "... SharedLibraries/mapFunctions.s"
	@echo "... SharedMemory/Pointer.o"
	@echo "... SharedMemory/Pointer.i"
	@echo "... SharedMemory/Pointer.s"
	@echo "... SharedMemory/PointerList.o"
	@echo "... SharedMemory/PointerList.i"
	@echo "... SharedMemory/PointerList.s"
	@echo "... SharedMemory/SharedMemoryGenerator.o"
	@echo "... SharedMemory/SharedMemoryGenerator.i"
	@echo "... SharedMemory/SharedMemoryGenerator.s"
	@echo "... SharedMemory/resources/SharedMemoryData.o"
	@echo "... SharedMemory/resources/SharedMemoryData.i"
	@echo "... SharedMemory/resources/SharedMemoryData.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

